Download platforms individually if required

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,5 +1,5 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by ActionBuilderTool 2.0.2 (82).
+# This workflow was automatically generated by ActionBuilderTool 2.1.0 (83).
 # (see https://github.com/elegantchaos/ActionBuilderCore for more details)
 # --------------------------------------------------------------------------------
 
@@ -23,8 +23,14 @@ jobs:
           run: swift --version
         - name: Build (release)
           run: swift build --configuration release --quiet
-        - name: Test (release)
-          run: swift test --configuration release --quiet
+        - name: Test (release XCTest)
+          run: |
+            set -o pipefail
+            swift test --disable-swift-testing --configuration release --quiet
+        - name: Test (release Swift Testing)
+          run: |
+            set -o pipefail
+            swift test --disable-xctest --configuration release --quiet
 
 
     macOS-swift62:
@@ -43,8 +49,14 @@ jobs:
           run: swift --version
         - name: Build (release)
           run: swift build --configuration release --quiet
-        - name: Test (release)
-          run: swift test --configuration release | xcbeautify --disable-logging --renderer github-actions
+        - name: Test (release XCTest)
+          run: |
+            set -o pipefail
+            swift test --disable-swift-testing --configuration release | xcbeautify --disable-logging --renderer github-actions
+        - name: Test (release Swift Testing)
+          run: |
+            set -o pipefail
+            swift test --disable-xctest --configuration release | xcbeautify --disable-logging --renderer github-actions
 
 
     xcode-swift62:
@@ -59,7 +71,6 @@ jobs:
             sudo xcode-select -s /Applications/Xcode_26.0.0.app
             xcodebuild -version
             swift --version
-            xcodebuild --downloadAllPlatforms
         - name: Make Logs Directory
           run: mkdir logs
         - name: Detect Workspace & Scheme (iOS)
@@ -67,66 +78,69 @@ jobs:
             WORKSPACE="Logger.xcworkspace"
             if [[ ! -e "$WORKSPACE" ]]
             then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Logger-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Logger-Package"
+              WORKSPACE="."
+              GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Logger-Package || true))
+              if [[ $GOTPACKAGE != "" ]]
+              then
+                SCHEME="Logger-Package"
+              else
+                SCHEME="Logger"
+              fi
             else
-            SCHEME="Logger"
+              SCHEME="Logger-iOS"
             fi
-            else
-            SCHEME="Logger-iOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform iOS" > setup.sh
         - name: Test (iOS Release)
           run: |
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            set -o pipefail
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 16" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (tvOS)
           run: |
             WORKSPACE="Logger.xcworkspace"
             if [[ ! -e "$WORKSPACE" ]]
             then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Logger-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Logger-Package"
+              WORKSPACE="."
+              GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Logger-Package || true))
+              if [[ $GOTPACKAGE != "" ]]
+              then
+                SCHEME="Logger-Package"
+              else
+                SCHEME="Logger"
+              fi
             else
-            SCHEME="Logger"
+              SCHEME="Logger-tvOS"
             fi
-            else
-            SCHEME="Logger-tvOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform tvOS" > setup.sh
         - name: Test (tvOS Release)
           run: |
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            set -o pipefail
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV 4K (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcbeautify --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (watchOS)
           run: |
             WORKSPACE="Logger.xcworkspace"
             if [[ ! -e "$WORKSPACE" ]]
             then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Logger-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Logger-Package"
+              WORKSPACE="."
+              GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Logger-Package || true))
+              if [[ $GOTPACKAGE != "" ]]
+              then
+                SCHEME="Logger-Package"
+              else
+                SCHEME="Logger"
+              fi
             else
-            SCHEME="Logger"
+              SCHEME="Logger-watchOS"
             fi
-            else
-            SCHEME="Logger-watchOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform watchOS" > setup.sh
         - name: Build (watchOS release)
           run: |
             source "setup.sh"
             echo "Building workspace $WORKSPACE scheme $SCHEME."
+            set -o pipefail
             xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 10 (42mm)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcbeautify --disable-logging --renderer github-actions
         - name: Upload Logs
           uses: actions/upload-artifact@v4
