More compact workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,5 +1,5 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by ActionBuilderTool 2.1.0 (83).
+# This workflow was automatically generated by ActionBuilderTool 2.1.0 (90).
 # (see https://github.com/elegantchaos/ActionBuilderCore for more details)
 # --------------------------------------------------------------------------------
 
@@ -15,11 +15,13 @@ jobs:
         steps:
         - name: Checkout
           uses: actions/checkout@v4
+        - name: Make Logs Directory
+          run: mkdir logs
         - name: Select Swift
           uses: beeauvin/swiftly-swift@v1
           with:
             swift-version: "6.2-snapshot"
-        - name: Check Swift Version
+        - name: Swift Version
           run: swift --version
         - name: Build (release)
           run: swift build --configuration release --quiet
@@ -41,22 +43,24 @@ jobs:
           uses: actions/checkout@v4
         - name: Install xcbeautify
           run: brew install xcbeautify
+        - name: Make Logs Directory
+          run: mkdir logs
         - name: Select Swift
           uses: beeauvin/swiftly-swift@v1
           with:
             swift-version: "6.2-snapshot"
-        - name: Check Swift Version
+        - name: Swift Version
           run: swift --version
         - name: Build (release)
           run: swift build --configuration release --quiet
         - name: Test (release XCTest)
           run: |
             set -o pipefail
-            swift test --disable-swift-testing --configuration release | xcbeautify --disable-logging --renderer github-actions
+            swift test --disable-swift-testing --configuration release | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Test (release Swift Testing)
           run: |
             set -o pipefail
-            swift test --disable-xctest --configuration release | xcbeautify --disable-logging --renderer github-actions
+            swift test --disable-xctest --configuration release | xcbeautify --quiet --disable-logging --renderer github-actions
 
 
     xcode-swift62:
@@ -65,14 +69,16 @@ jobs:
         steps:
         - name: Checkout
           uses: actions/checkout@v4
+        - name: Install xcbeautify
+          run: brew install xcbeautify
+        - name: Make Logs Directory
+          run: mkdir logs
         - name: Select Xcode Version
           run: |
-            ls -d /Applications/Xcode*
+            ls -d /Applications/Xcode* > logs/xcode-versions.log
             sudo xcode-select -s /Applications/Xcode_26.0.0.app
             xcodebuild -version
             swift --version
-        - name: Make Logs Directory
-          run: mkdir logs
         - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="Logger.xcworkspace"
@@ -89,13 +95,13 @@ jobs:
             else
               SCHEME="Logger-iOS"
             fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform iOS" > setup.sh
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform iOS > logs/download-iOS.log; xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showdestinations > logs/destinations-iOS.log" > setup.sh
         - name: Test (iOS Release)
           run: |
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 16" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --disable-logging --renderer github-actions
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone SE (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (tvOS)
           run: |
             WORKSPACE="Logger.xcworkspace"
@@ -112,13 +118,13 @@ jobs:
             else
               SCHEME="Logger-tvOS"
             fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform tvOS" > setup.sh
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform tvOS > logs/download-tvOS.log; xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showdestinations > logs/destinations-tvOS.log" > setup.sh
         - name: Test (tvOS Release)
           run: |
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV 4K (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcbeautify --disable-logging --renderer github-actions
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV 4K (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (watchOS)
           run: |
             WORKSPACE="Logger.xcworkspace"
@@ -135,17 +141,17 @@ jobs:
             else
               SCHEME="Logger-watchOS"
             fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform watchOS" > setup.sh
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform watchOS > logs/download-watchOS.log; xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showdestinations > logs/destinations-watchOS.log" > setup.sh
         - name: Build (watchOS release)
           run: |
             source "setup.sh"
             echo "Building workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 10 (42mm)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcbeautify --disable-logging --renderer github-actions
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 10 (42mm)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Upload Logs
           uses: actions/upload-artifact@v4
           if: always()
           with:
-            name: logs
+            name: xcode-swift62-logs
             path: logs
 
